### ISSUE TITLE
please allow megaparsec 9

### ISSUE THREAD

**Issue by juhp** [egison/egison-pattern-src#25]
Stackage Nightly is currently blocked on updating to megaparsec 9 because of this.

commercialhaskell/stackage#5632

**Comment by momohatt** [comment]
@juhp Thanks for letting us know! We've just released v0.2.1.2 with support of megaparsec v9.

**Comment by juhp** [comment]
Just FYI: https://www.stackage.org/nightly-2020-11-08/package/egison-pattern-src-0.2.1.2
